### PR TITLE
docs for text-node-style comments

### PR DESCRIPTION
**Pull request by jonschlinkert**
@dpashkevich please review, I'd love your feedback

### CODE REVIEW

**Comment by dpashkevich** [comment]
At a first glance looks ok to me. Can be a candidate for the initial implementation if we don't think about some edge cases. 

Still don't like the idea of rendering `/* block comments */` to html, though... But we have to try it out in practice.

A closer look on the suggested implementations raises some concerns.
This syntax:

``` css
.content {
  text: "Welcome to our site!";
  comment: "Hello, I'm a text comment."; // this comment will be appended to the text node after the text
}
```

Makes `text` and `comment` look like they're attributes, as in:

``` css
a {
  href: "http://google.com",
  target: "Blank"
}
```

But comments and text **nodes** are actually closer to elements (they are DOM nodes). They don't behave like attributes because an element can have multiple comments and multiple text nodes inside it (but can't have multiple attributes with the same name, it doesn't make sense).

So this time I'll start from the other end of the stick. How would you encode this in Pre?

``` html
<p>
    <!-- I am a comment -->
    Welcome to our site! We love <strong>bold text</bold>.<br />
    <!-- I am a comment too... -->
    Feel free to browse around.
</p>
```

With what we have now it would be something like:

``` css
p {
    comment: 'I am a comment';
    text: 'Welcome to our site! We love ';
    strong: {
        text: 'bold text';
    }
    text: '.';
    br {}
    comment: 'I am a comment too...';
    text: 'Feel free to browse around.';
}
```

Ugh, yuck! That does not look better (and shorter) than html!))) Of course the worst par here isn't even mixing text and comment nodes (which is uncommon, I believe), but having blocks of text with formatting (i.e. bold, italic, underline, links, etc.). And the latter does look real enough: you find it all the times in article content. 

Manually putting paragraphs and inline elements like `strong`, `em`, `a`, `code` when writing an article (i.e. creating content, not doing a webpage layout) is a big PITA and that's why there is Markdown and friends (Textile, ReSt, etc) that are better suited for content. Obviously, Pre doesn't have a good solution here at the moment.

So this situation raises some important questions:
- Is Pre intended to be used for creating whole pages (basically, as a full substitute to HTML) or is more of a templating engine?
- The former is of course more challenging but more interesting as well and would bring more value to the language (i.e. not just a fork of Jade that has curly braces and is a little easier to learn). So if we go the first way, how can Pre facilitate creating long blocks of text (and comments if you love them :))?

Parts of the solution can be:
- Heredoc syntax for creating long **plain**text nodes (see #11)
  - But as emphasized, this only works well with plain text with no formatting. As soon as you attempt adding text formatting capabilities to that syntax (allow html??? nah...), you run the risk of forcing the user to escape certain characters (I wouldn't want that)
- We should somehow allow placing text nodes and tags side by side, e.g.

``` css
p {
   text {}
   a {}
   text {}
   span {}
   text {} 
}
```

This would still be useful in some cases but not for long article content
- As I noted above, I feel that the syntax for text nodes (and html comments alike) should be closer to elements than attributes (e.g. `text { SOMETHING HERE }`, not `text: 'Hello'`)
- It appears that doing webpage layout and filling it with content (the payload) are different things. So what's good to use for layout isn't necessarily good for content and vice versa.
- This brings me to a wild idea: if Pre claims to allow people do both, maybe we can allow Markdown for writing text?

Compiling everything said above, I came to the following proposal for "text nodes" syntax (in quotes cause it's not necessarily plain text with this approach):

``` css
article {
    text: {<<<md

## Credits

* Jade: This documenation draws heavily upon the docs for [Jade](https://github.com/visionmedia/pre), credit goes to [TJ Holowaychuk ](https://github.com/visionmedia) and the contributors of Jade
* LESS
* HAML
* Jekyll
* ZenCoding
* Mustache

    <<<}
}
```

The essense of it is this line:

```
 text: {<<<md
```

Clearly inspired by Github's Markdown syntax for code blocks :) 
- `<<<` works like three backticks ``` 
- `md` is clearly a keyword for Markdown. We can support multiple text formatting plugins here!
- If you want just plain text you don't specify any keyword after `<<<` or you put something like `<<<plain`

Phew :) Looks like I deviated a little bit from the comment syntax topic but it seems to be intertwined with the text node syntax topic with the broader layout and content topic)

**Comment by dpashkevich** [comment]
Oh and #26 should help us catch more issues like this :)

**Comment by jonschlinkert** [comment]
I agree on the markdown, I was thinking something similar. We wouldn't we just do this?

``` css
article {
    markdown: "...";
}
```

Markdown really isn't "text" strictly speaking. 

And I think we're over-complicating things here, regarding text and comments. Text and comments are DOM nodes, so let's just add curly braces and make them DOM nodes in Pre. 

``` css
p {
    text: {}
}
```

To the point you were making with the long and messy code example, you raise good points, but it wouldn't be difficult to intentionally write bad (or worse) code in CSS, HTML, Jade or anything else.  The point of Pre is not expressly to "always" be more concise than HTML, but rather to have access to dynamic features that HTML does not have natively: mixins, variables, operations, etc. So while you might find a messy block of code now and then in any language, I can rebut with this (a full page in Pre, bootstrap-style):

``` css
!!! 5  // same DOCTYPE lexicon as Jade
html {  // also, I could make the entire head a mixin and get rid of this block...
  lang: "en";
  head {
    title {
      text: { "Page Title"; }
    }
    .docsStyles();
    .docsHeadScripts();
  } 
  body {
    .topnav();
    .container {
      .row {
        .span3 {
          .sidenav();
        }
        .span9 {
          .pageheader();
          .content(); // clearly this would be more specific, like .homePageContent(); etc.
        }
      }
    }
    script {
      src: "assets/js/app.js";
      .docsScripts();
    }
  }
}
```

Or this:

``` css
!!! 5 .home();
!!! 5 .about();
!!! 5 .contact();
```

Show me something more concise in Jade! lol jk.

And the following is why I want to convert block comments to html :)  

``` css
p {
    /* 'I am a comment'; */
    text: 'Welcome to our site! We love ';
    strong: {
        text: 'bold text';
    }
    text: '.';
    br {}
    /* 'I am a comment too...'; */
    text: 'Feel free to browse around.';
}
```

I don't see a need for anything more.  Block comments even work inline with text:

``` css
p {
    /* 'I am a comment'; */
    text: 'Welcome to our site!  /* 'I am a comment'; */  We  /* 'I am a comment'; */  love ';  /* 'I am a comment'; */ 
    strong: {
        text: 'bold  /* 'I am a comment'; */  text';
    }
}
 /* 'I am a comment'; */
```

Too many code comments always looks messy, no way around it.

**Comment by jonschlinkert** [comment]
@doowb any thoughts on this?

**Comment by jonschlinkert** [comment]
@dpashkevich one thing to keep in mind is that there are very few things (regarding static HTML, not templating etc) which cannot be targeted specifically in HTML with CSS. This is what makes jQuery and other selector engines so effective.

For instance, remember that CSS already has a paradigm for inserting text (in a text node, DOM element as you point out):

``` css
article {
    content: "...";  // generated content shows up in the text node
}
```

And if we use your style of comments, we can target exactly where we want the comment(s) to show up ( element:

``` css
article {
    content: "..."; 
    &:before {
        comment: "...";
    }
}
```

Is that more code than HTML? You can't quantify it one-to-one because blocks of code in Pre can be reused and compile into HTLM. I could make the same argument for any number of mixins in LESS or SASS... But mixins aren't intended to represent a one-to-one translation to CSS.

As for writing long and complicated blocks of content, no problem at all. But I think that more often than not it would look more like this than what you were imagining in your example:

``` css
article {
    .mixinForContent(); // syntax is irrelevant to the point here, it could be any syntax
}
```

and then elsewhere, probably in a document specified for this purpose:

``` css
// this could look as hairy and complicated as you want or need it to look... same goes for straight HTML
.mixinForContent(); {...}
```

I'm curious about the following though...  Is it really necessary to overly specify things like markdown, template syntax, pre-formatted text or code using a different syntax, like `<<<md`?  It seems that we already have delimiters that should work: `";}`

I have an idea for handling messy code, I think we should consider using the "import" feature of CSS for includes, or some other way of handling includes. That way you could specify an external block of code, or external file which contains Pre or even straight HTML and have it inserted during the build. So it's similar to a mixin, but works more like a partial. I think Jade has something similar... 

ah, here it is: http://tjholowaychuk.com/post/7590787973/jade-mixins-includes

**Pull request merged**
